before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/sealyun-market/sealos-cri-shim/pkg/version.gitVersion={{.Version}}
      - -X github.com/sealyun-market/sealos-cri-shim/pkg/version.gitCommit={{.ShortCommit}}
      - -X github.com/sealyun-market/sealos-cri-shim/pkg/version.buildDate={{.Date}}
      - -s -w
archives:
  - id: default
    builds:
      - sealos-cri-shim
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    format: tar.gz
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
