shim: /var/run/image-cri-shim.sock
cri: /run/containerd/containerd.sock
address: sealos.hub:5000
force: true
debug: false
image: /Users/cuisongliu/Workspaces/go/src/github.com/sealyun-market/sealos-cri-shim/config/images
