name: CI

env:
  # Common versions
  GO_VERSION: '1.16'

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
    paths-ignore:
      - 'docs/**'
      - 'vendor/**'
      - '*.md'
      - '*.yml'
jobs:

  build-binaries:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: build --snapshot --rm-dist  --timeout=1h
      - name: Save build binaries linux-amd64
        uses: actions/upload-artifact@v2
        with:
          name: sealos-amd64
          path: dist/sealos_linux_amd64/sealos
      - name: Save build binaries linux-arm64
        uses: actions/upload-artifact@v2
        with:
          name: sealos-arm64
          path: dist/sealos_linux_arm64/sealos
